(package! typo)
(package! elpy)
(package! elmacro)
(package! abbrev)
(package! wordnut)
(package! clipmon)
(package! delight)
(package! org2blog)
(package! olivetti)
(package! ehich-key)
(package! org-brain)
(package! caps-lock)
(package! eyebrowse)
(package! vimrc-mode)
(package! super-save)
(package! lorem-ipsum)
(package! hl-sentence)
(package! fountain-mode)
(package! url-shortener)
(package! evil-swap-keys)
(package! evil-god-state)
(package! evil-smartparens)
(package! artbollocks-mode)
(package! google-translate)
(package! recursive-narrow)
(package! electric-operator)
(package! git-auto-commit-mode)
(package! engine-mode :pin "e0910f1")
(package! apheleia :recipe (:host github :repo "raxod502/apheleia"))

(package! zoom :disable t)
(package! beacon :disable t)
(package! shut-up :disable t)
(package! nswbuff :disable t)
(package! polymode :disable t)
(package! org-roam :disable t)
(package! evil-lion :disable t)
(package! yafolding :disable t)
(package! evil-snipe :disable t)
(package! bug-hunter :disable t)
(package! org-web-tools :disable t)
(package! ivy-yasnippet :disable t)
(package! benchmark-init :disable t)
(package! unkillable-scratch :disable t)
(package! evil-better-visual-line :disable t)
