(define-key key-translation-map (kbd "º") (kbd"-"))
(define-key key-translation-map (kbd "s-8") (kbd"["))
(define-key key-translation-map (kbd "s-9") (kbd"]"))
(define-key key-translation-map (kbd "s-(") (kbd"{"))
(define-key key-translation-map (kbd "s-)") (kbd"}"))
(define-key key-translation-map (kbd "<help>") (kbd"<insert>"))
