;;-*-coding: utf-8;-*-
(define-abbrev-table 'emacs-lisp-mode-abbrev-table
  '(
    ("cot" ";;;; ;;;;" nil :count 1)
    ("head" ";;;; * " nil :count 1)
   ))

(define-abbrev-table 'global-abbrev-table
  '(
    ("chao" "chão" nil :count 6)
    ("nao" "não" nil :count 34)
   ))

(define-abbrev-table 'markdown-mode-abbrev-table
  '(
    ("admitedly" "admittedly" nil :count 0)
    ("aqeual" "aquela" nil :count 0)
    ("articial" "artificial" nil :count 0)
    ("ateh" "até" nil :count 0)
    ("atomico" "atômico" nil :count 0)
    ("balcao" "balcão" nil :count 0)
    ("bebados" "bêbados" nil :count 0)
    ("benefitial" "beneficial" nil :count 0)
    ("cabeca" "cabeça" nil :count 0)
    ("cacorro" "cachorro" nil :count 0)
    ("casaa" "casa" nil :count 1)
    ("cesar" "césar" nil :count 0)
    ("comemoracao" "comemoração" nil :count 0)
    ("commentares" "commentaries" nil :count 0)
    ("conecting" "connecting" nil :count 0)
    ("diferenca" "diferença" nil :count 0)
    ("disscussions" "discussions" nil :count 0)
    ("distribuition" "distribution" nil :count 0)
    ("dowloading" "downloading" nil :count 0)
    ("eh" "é" nil :count 4)
    ("exaustive" "exhaustive" nil :count 0)
    ("imho" "imho" nil :count 1)
    ("inteliffenge" "intelligent" nil :count 0)
    ("intereseting" "interesting" nil :count 0)
    ("intuitite" "intuitive" nil :count 0)
    ("julio" "júlio" nil :count 0)
    ("linux" "Linux" nil :count 2)
    ("measuremente" "measurement" nil :count 0)
    ("nao" "não" nil :count 7)
    ("neverthless" "nevertheless" nil :count 0)
    ("nivel" "nível" nil :count 0)
    ("oceanica" "oceânica" nil :count 0)
    ("ot" "of" nil :count 0)
    ("particpa" "participa" nil :count 0)
    ("quimicas" "químicas" nil :count 0)
    ("reacoes" "reações" nil :count 0)
    ("refered" "refereed" nil :count 0)
    ("retangulo" "retângulo" nil :count 1)
    ("subjetcs" "subjects" nil :count 0)
    ("tah" "tá" nil :count 0)
    ("termrs" "terms" nil :count 0)
    ("tipically" "typically" nil :count 0)
    ("tres" "três" nil :count 0)
    ("voce" "você" nil :count 7)
    ("whill" "will" nil :count 0)
    ("wich" "which" nil :count 0)
    ("youll" "you'll" nil :count 0)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("acao" "ação" nil :count 0)
    ("acompnhar" "acompanhar" nil :count 0)
    ("adrogina" "andrógina" nil :count 0)
    ("agrupamnto" "agrupamento" nil :count 0)
    ("alcancados" "alcançados" nil :count 0)
    ("alem" "além" nil :count 0)
    ("alguem" "alguém" nil :count 0)
    ("alí" "ali" nil :count 0)
    ("ambientacao" "ambientação" nil :count 0)
    ("ameacador" "ameaçador" nil :count 0)
    ("ameacas" "ameaças" nil :count 0)
    ("aperfeicoando" "aperfeiçoando" nil :count 0)
    ("apresenacao" "apresentação" nil :count 0)
    ("armacao" "armação" nil :count 0)
    ("ateh" "até" nil :count 4)
    ("atencao" "atenção" nil :count 2)
    ("ausencia" "ausência" nil :count 0)
    ("avancadas" "avançadas" nil :count 0)
    ("avancos" "avanços" nil :count 0)
    ("biceps" "bíceps" nil :count 0)
    ("cabeca" "cabeça" nil :count 4)
    ("caracteristico" "característico" nil :count 0)
    ("catatonicos" "catatônicos" nil :count 0)
    ("cenario" "cenário" nil :count 1)
    ("chanche" "chance" nil :count 0)
    ("comeca" "começa" nil :count 0)
    ("comecar" "começar" nil :count 0)
    ("completemante" "completamente" nil :count 0)
    ("condicao" "condição" nil :count 0)
    ("conduzilo" "conduzí-lo" nil :count 0)
    ("conduzí-lo" "conduzi-lo" nil :count 0)
    ("consequece" "consegue" nil :count 0)
    ("convivado" "convidado" nil :count 0)
    ("coracao" "coração" nil :count 0)
    ("criacao" "criação" nil :count 0)
    ("dah" "dá" nil :count 5)
    ("dao" "dão" nil :count 0)
    ("descricao" "descrição" nil :count 2)
    ("desgradável" "desagradável" nil :count 0)
    ("detras" "detrás" nil :count 0)
    ("dialogos" "diálogos" nil :count 1)
    ("dinamica" "dinâmica" nil :count 0)
    ("direcao" "direção" nil :count 1)
    ("direcionalo" "direcioná-lo" nil :count 0)
    ("educacao" "educação" nil :count 0)
    ("eh" "é" nil :count 30)
    ("eletronica" "eletrônica" nil :count 0)
    ("espacosa" "espaciosa" nil :count 0)
    ("espreguica" "espreguiça" nil :count 0)
    ("esqualido" "esquálido" nil :count 0)
    ("esquedo" "esquerdo" nil :count 0)
    ("estah" "está" nil :count 8)
    ("estao" "estão" nil :count 0)
    ("estrassante" "estressante" nil :count 0)
    ("exercicios" "exercícios" nil :count 0)
    ("exl" "* External Links" nil :count 1)
    ("exoneracao" "exoneração" nil :count 0)
    ("exoticos" "exóticos" nil :count 0)
    ("farah" "fará" nil :count 0)
    ("fisica" "física" nil :count 0)
    ("fisicos" "físicos" nil :count 0)
    ("frequencia" "frequência" nil :count 0)
    ("funcionalides" "funcionalidades" nil :count 0)
    ("garantindolhe" "garantindo-lhe" nil :count 0)
    ("havera" "haverá" nil :count 0)
    ("impossiveis" "impossíveis" nil :count 0)
    ("indetectaveis" "indetectáveis" nil :count 0)
    ("infancia" "infância" nil :count 0)
    ("injeva" "inveja" nil :count 0)
    ("inl" "* Internal Links" nil :count 1)
    ("insegurancas" "inseguranças" nil :count 0)
    ("insistencia" "insistência" nil :count 0)
    ("interacao" "interação" nil :count 0)
    ("interim" "ínterim" nil :count 0)
    ("inumeras" "inúmeras" nil :count 0)
    ("irmao" "irmão" nil :count 0)
    ("ja" "já" nil :count 1)
    ("jah" "já" nil :count 2)
    ("labios" "lábios" nil :count 0)
    ("luana" "Luana" nil :count 36)
    ("luiza" "luíza" nil :count 0)
    ("mae" "mãe" nil :count 0)
    ("mansao" "mansão" nil :count 0)
    ("mao" "mão" nil :count 2)
    ("mariana" "Mariana" nil :count 44)
    ("metodo" "método" nil :count 0)
    ("motivacao" "motivação" nil :count 0)
    ("mudancas" "mudanças" nil :count 0)
    ("mulheh" "mulher" nil :count 0)
    ("nance" "nance" nil :count 1)
    ("necessario" "necessário" nil :count 0)
    ("ninguem" "ninguém" nil :count 0)
    ("oculos" "óculos" nil :count 2)
    ("opcao" "opção" nil :count 0)
    ("opcoes" "opções" nil :count 0)
    ("organizacao" "organização" nil :count 0)
    ("paixao" "paixão" nil :count 0)
    ("pao" "pão" nil :count 1)
    ("parametros" "parâmetros" nil :count 0)
    ("pedro" "Pedro" nil :count 15)
    ("peh" "pé" nil :count 0)
    ("pessimo" "péssimo" nil :count 0)
    ("possiveis" "possíveis" nil :count 0)
    ("possivel" "possível" nil :count 0)
    ("praca" "praça" nil :count 0)
    ("predilecao" "predileção" nil :count 0)
    ("propria" "própria" nil :count 0)
    ("proprias" "próprias" nil :count 0)
    ("proxima" "próxima" nil :count 1)
    ("questao" "questão" nil :count 0)
    ("ralias" "#+roam_alias:" nil :count 2)
    ("razovelmente" "razoavelmente" nil :count 0)
    ("reforco" "reforço" nil :count 0)
    ("relacionemnto" "relacionamento" nil :count 0)
    ("resolucao" "resolução" nil :count 0)
    ("resutado" "resultado" nil :count 0)
    ("rkeys" "#+roam_key:" nil :count 2)
    ("rtags" "#+roam_tags:" nil :count 1)
    ("saida" "saída" nil :count 0)
    ("saih" "saí" nil :count 0)
    ("sanitario" "sanitário" nil :count 0)
    ("sao" "são" nil :count 4)
    ("satisfatorio" "satisfatório" nil :count 0)
    ("segio" "sérgio" nil :count 0)
    ("seguranca" "segurança" nil :count 0)
    ("senao" "senão" nil :count 0)
    ("serah" "será" nil :count 0)
    ("sergio" "Sérgio" nil :count 19)
    ("sergrio" "sérgio" nil :count 0)
    ("servico" "serviço" nil :count 0)
    ("situacao" "situação" nil :count 1)
    ("so" "só" nil :count 2)
    ("socidade" "sociedade" nil :count 0)
    ("sofas" "sofás" nil :count 0)
    ("soh" "só" nil :count 3)
    ("sérgio" "Sérgio" nil :count 12)
    ("tah" "tá" nil :count 4)
    ("tambem" "também" nil :count 2)
    ("tecnicos" "técnicos" nil :count 0)
    ("tedio" "tédio" nil :count 0)
    ("televisao" "televisão" nil :count 0)
    ("tornandose" "tornando-se" nil :count 0)
    ("tres" "três" nil :count 2)
    ("ve" "vê" nil :count 0)
    ("veh" "vê" nil :count 3)
    ("voce" "você" nil :count 14)
   ))

(define-abbrev-table 'snippet-mode-abbrev-table
  '(
    ("expand" "# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))" nil :count 1)
   ))

