;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("chao" "chão" nil :count 6)
    ("nao" "não" nil :count 19)
   ))

(define-abbrev-table 'markdown-mode-abbrev-table
  '(
    ("aqeual" "aquela" nil :count 0)
    ("ateh" "até" nil :count 0)
    ("atomico" "atômico" nil :count 0)
    ("balcao" "balcão" nil :count 0)
    ("bebados" "bêbados" nil :count 0)
    ("benefitial" "beneficial" nil :count 0)
    ("cabeca" "cabeça" nil :count 0)
    ("cacorro" "cachorro" nil :count 0)
    ("casaa" "casa" nil :count 1)
    ("cesar" "césar" nil :count 0)
    ("comemoracao" "comemoração" nil :count 0)
    ("conecting" "connecting" nil :count 0)
    ("diferenca" "diferença" nil :count 0)
    ("dowloading" "downloading" nil :count 0)
    ("eh" "é" nil :count 4)
    ("imho" "imho" nil :count 1)
    ("intuitite" "intuitive" nil :count 0)
    ("julio" "júlio" nil :count 0)
    ("nao" "não" nil :count 7)
    ("nivel" "nível" nil :count 0)
    ("oceanica" "oceânica" nil :count 0)
    ("particpa" "participa" nil :count 0)
    ("quimicas" "químicas" nil :count 0)
    ("reacoes" "reações" nil :count 0)
    ("retangulo" "retângulo" nil :count 1)
    ("tah" "tá" nil :count 0)
    ("tres" "três" nil :count 0)
    ("voce" "você" nil :count 7)
    ("youll" "you'll" nil :count 0)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("acao" "ação" nil :count 0)
    ("adrogina" "andrógina" nil :count 0)
    ("agrupamnto" "agrupamento" nil :count 0)
    ("alem" "além" nil :count 0)
    ("alguem" "alguém" nil :count 0)
    ("ambientacao" "ambientação" nil :count 0)
    ("ameacador" "ameaçador" nil :count 0)
    ("ameacas" "ameaças" nil :count 0)
    ("aperfeicoando" "aperfeiçoando" nil :count 0)
    ("apresenacao" "apresentação" nil :count 0)
    ("armacao" "armação" nil :count 0)
    ("ateh" "até" nil :count 1)
    ("avancadas" "avançadas" nil :count 0)
    ("cabeca" "cabeça" nil :count 1)
    ("caracteristico" "característico" nil :count 0)
    ("catatonicos" "catatônicos" nil :count 0)
    ("cenario" "cenário" nil :count 1)
    ("chanche" "chance" nil :count 0)
    ("comecar" "começar" nil :count 0)
    ("completemante" "completamente" nil :count 0)
    ("condicao" "condição" nil :count 0)
    ("conduzilo" "conduzí-lo" nil :count 0)
    ("conduzí-lo" "conduzi-lo" nil :count 0)
    ("consequece" "consegue" nil :count 0)
    ("coracao" "coração" nil :count 0)
    ("criacao" "criação" nil :count 0)
    ("dah" "dá" nil :count 3)
    ("dao" "dão" nil :count 0)
    ("descricao" "descrição" nil :count 2)
    ("dialogos" "diálogos" nil :count 1)
    ("dinamica" "dinâmica" nil :count 0)
    ("direcionalo" "direcioná-lo" nil :count 0)
    ("eh" "é" nil :count 20)
    ("espacosa" "espaciosa" nil :count 0)
    ("espreguica" "espreguiça" nil :count 0)
    ("esqualido" "esquálido" nil :count 0)
    ("esquedo" "esquerdo" nil :count 0)
    ("estah" "está" nil :count 4)
    ("exl" "* External Links" nil :count 1)
    ("exoticos" "exóticos" nil :count 0)
    ("funcionalides" "funcionalidades" nil :count 0)
    ("garantindolhe" "garantindo-lhe" nil :count 0)
    ("havera" "haverá" nil :count 0)
    ("indetectaveis" "indetectáveis" nil :count 0)
    ("inl" "* Internal Links" nil :count 1)
    ("interacao" "interação" nil :count 0)
    ("irmao" "irmão" nil :count 0)
    ("ja" "já" nil :count 0)
    ("luiza" "luíza" nil :count 0)
    ("mae" "mãe" nil :count 0)
    ("mansao" "mansão" nil :count 0)
    ("mao" "mão" nil :count 1)
    ("mariana" "Mariana" nil :count 22)
    ("metodo" "método" nil :count 0)
    ("oculos" "óculos" nil :count 0)
    ("opcao" "opção" nil :count 0)
    ("opcoes" "opções" nil :count 0)
    ("organizacao" "organização" nil :count 0)
    ("pao" "pão" nil :count 1)
    ("pedro" "Pedro" nil :count 15)
    ("peh" "pé" nil :count 0)
    ("pessimo" "péssimo" nil :count 0)
    ("possiveis" "possíveis" nil :count 0)
    ("possivel" "possível" nil :count 0)
    ("praca" "praça" nil :count 0)
    ("propria" "própria" nil :count 0)
    ("proprias" "próprias" nil :count 0)
    ("proxima" "próxima" nil :count 1)
    ("questao" "questão" nil :count 0)
    ("ralias" "#+roam_alias:" nil :count 2)
    ("razovelmente" "razoavelmente" nil :count 0)
    ("resolucao" "resolução" nil :count 0)
    ("resutado" "resultado" nil :count 0)
    ("rkeys" "#+roam_key:" nil :count 2)
    ("rtags" "#+roam_tags:" nil :count 1)
    ("saida" "saída" nil :count 0)
    ("sanitario" "sanitário" nil :count 0)
    ("sao" "são" nil :count 3)
    ("satisfatorio" "satisfatório" nil :count 0)
    ("seguranca" "segurança" nil :count 0)
    ("serah" "será" nil :count 0)
    ("sergio" "sérgio" nil :count 3)
    ("situacao" "situação" nil :count 1)
    ("so" "só" nil :count 1)
    ("sofas" "sofás" nil :count 0)
    ("tambem" "também" nil :count 1)
    ("tecnicos" "técnicos" nil :count 0)
    ("televisao" "televisão" nil :count 0)
    ("todo" "TODO" nil :count 6)
    ("tres" "três" nil :count 2)
    ("ve" "vê" nil :count 0)
    ("veh" "vê" nil :count 1)
    ("voce" "você" nil :count 2)
   ))

(define-abbrev-table 'snippet-mode-abbrev-table
  '(
    ("expand" "# expand-env: ((yas-indent-line 'fixed) (yas-wrap-around-region 'nil))" nil :count 1)
   ))

